#!/usr/bin/env bash
# installing nginx

sudo apt update
sudo apt install nginx
mkdir /etc/nginx/static_content/
touch /etc/nginx/static_content/index.html
echo "Hello World!" > /etc/nginx/static_content/index.html
printf %s "server {
        listen 80;
        listen [::]:80 default_server;
	root /etc/nginx/static_content
	index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart
