#!/usr/bin/env bash
# Installs HAProxy and configure it
 
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get update
apt-get install -y haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo  /etc/haproxy/haproxy.cfg
frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend apache_webservers    
backend apache_webservers
    balance roundrobin
    server web-01	18.207.236.125 check
    server web-02	02 35.196.46.172:80 check
service haproxy start
