#!/usr/bin/env bash
# display some fields
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
	unset password groupid comment cmdshell
	echo "$username:$userid:$homedir $password $groupid $comment $cmdshell"
done < $FILENAME
