#!/usr/bin/env bash
# print 20 times and some superstitious numbers 
itr=1
while [ $itr -le 20 ];
do
	echo "$itr"
	case $itr in
	       	"4")		
		echo "bad luck from China";;
		"9")
		echo "bad luck from Japan";;
		"17")
		echo "bad luck from Italy";;
	esac
	((itr++))
done
