#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 18.207.236.125/22
sudo ufw allow 18.207.236.125/443
sudo ufw allow 18.207.236.125/80
