#!/usr/bin/env bash
# Runs the whoami command under the user passed as argument
if [ $# -ne 1 ]; then
  echo "Error: script requires exactly one argument (user name)"
  exit 1
fi
user=$1
result=$(su -c whoami $user)
echo "$result"
