#!/bin/bash
# Stop nginx service if running
sudo useradd -r nginx
sudo chown -R nginx:nginx /usr/share/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
http {
    server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
}
}
sudo service nginx restart
