#!/bin/bash



# Stop nginx service if running

service nginx stop

if ! id nginx &>/dev/null; then

	  useradd --system nginx

fi

cat > /etc/nginx/conf.d/default.conf <<EOF

server {

  listen 8080;

  listen [::]:8080;



  server_name _;

location / {

    root /var/www/html;

    index index.html index.htm;

  }

}

EOF

sed -i "s/user www-data;/user nginx nginx;/" /etc/nginx/nginx.conf
service nginx start
